<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);IL2026;IL3050;CA1822</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="coverlet.MTP" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.ValueObjects\EricksonLopez.ValueObjects.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.ValueObjects.Dapper\EricksonLopez.ValueObjects.Dapper.csproj" />
  </ItemGroup>
</Project>

