<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Dapper TypeHandler adapters for persistence of EricksonLopez.ValueObjects in relational databases like PostgreSQL.</Description>
    <PackageTags>$(CommonPackageTags);dapper;micro-orm;type-handler;sql;persistence;data-access</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EricksonLopez.ValueObjects\EricksonLopez.ValueObjects.csproj" />
  </ItemGroup>
</Project>
