// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using AwesomeAssertions;
using EricksonLopez.ValueObjects.Generators;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Xunit;

namespace EricksonLopez.ValueObjects.Generators.UnitTests;

public sealed class ValueObjectIncrementalGeneratorTests
{
    private const string ValueObjectAttributeSource = """
    namespace EricksonLopez.ValueObjects;

    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
    public sealed class ValueObjectAttribute : System.Attribute
    {
        public bool GenerateConversionOperators { get; set; }
    }
    """;

    private const string BaseInterfacesSource = """
    namespace EricksonLopez.ValueObjects;

    public interface IValueObject {}
    public interface IValueObject<TSelf> : IValueObject {}

    public abstract record ValueObject : IValueObject;

    public abstract record SingleValueObject<TSelf, TValue> : IValueObject<TSelf>
        where TSelf : SingleValueObject<TSelf, TValue>
        where TValue : notnull
    {
        public TValue Value { get; init; }
        protected SingleValueObject(TValue value) => Value = value;
    }

    public abstract record StringValueObject<TSelf> : SingleValueObject<TSelf, string>
        where TSelf : StringValueObject<TSelf>
    {
        protected StringValueObject(string value) : base(value) {}
    }
    """;

    [Fact]
    public void Generator_ShouldGenerateCode_ForRecordStruct()
    {
        var userSource = """
        namespace MyDomain;

        using EricksonLopez.ValueObjects;

        [ValueObject]
        public readonly partial record struct OrderId
        {
            public static EricksonLopez.Result.Result<OrderId> Create(string value) =>
                string.IsNullOrEmpty(value) ? EricksonLopez.Result.Result.Failure<OrderId>(EricksonLopez.Result.Error.Validation("Empty")) : EricksonLopez.Result.Result.Success(new OrderId());
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(1);
        var generated = generatedSources.First();
        generated.HintName.Should().Be("OrderId_ValueObject.g.cs");
        var code = generated.SourceText.ToString().Replace("\r\n", "\n");
        code.Should().Contain("// <auto-generated/>\n#nullable enable\n\nnamespace MyDomain\n{\n");
        code.Should().Contain("[global::System.Text.Json.Serialization.JsonConverter(typeof(OrderIdJsonConverter))]");
        code.Should().Contain("readonly partial record struct OrderId : global::System.IParsable<OrderId>, global::System.ISpanParsable<OrderId>, global::EricksonLopez.ValueObjects.IValueObject<OrderId>");
        code.Should().Contain("public static OrderId Parse(string s, global::System.IFormatProvider? provider = null)");
        code.Should().Contain("public static bool TryParse(string? s, global::System.IFormatProvider? provider, out OrderId result)");
        code.Should().Contain("public static OrderId Parse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider = null)");
        code.Should().Contain("public static bool TryParse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, out OrderId result)");
        code.Should().Contain("public sealed class OrderIdJsonConverter : global::System.Text.Json.Serialization.JsonConverter<OrderId>");
        code.Should().NotContain("operator");
    }

    [Fact]
    public void Generator_ShouldGenerateCode_ForRecordClass()
    {
        var userSource = """
        namespace MyDomain;


        [ValueObjectAttribute]
        public sealed partial record class CustomerName
        {
            public static EricksonLopez.Result.Result<CustomerName> Create(string value) =>
                EricksonLopez.Result.Result.Success(new CustomerName());
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(1);
        var generated = generatedSources.First();
        generated.HintName.Should().Be("CustomerName_ValueObject.g.cs");
        var code = generated.SourceText.ToString();
        code.Should().Contain("namespace MyDomain");
        code.Should().Contain("sealed partial record class CustomerName");
    }

    [Fact]
    public void Generator_ShouldGenerateCode_ForRegularStruct()
    {
        var userSource = """
        namespace MyDomain;

        [EricksonLopez.ValueObjects.ValueObject]
        public readonly partial struct SkuCode
        {
            public static EricksonLopez.Result.Result<SkuCode> Create(string value) =>
                EricksonLopez.Result.Result.Success(new SkuCode());
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(1);
        var generated = generatedSources.First();
        generated.HintName.Should().Be("SkuCode_ValueObject.g.cs");
        var code = generated.SourceText.ToString();
        code.Should().Contain("readonly partial struct SkuCode");
    }

    [Fact]
    public void Generator_ShouldGenerateCode_ForRegularClass()
    {
        var userSource = """
        namespace MyDomain;

        [EricksonLopez.ValueObjects.ValueObjectAttribute]
        public sealed partial class LegacyCode
        {
            public static EricksonLopez.Result.Result<LegacyCode> Create(string value) =>
                EricksonLopez.Result.Result.Success(new LegacyCode());
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(1);
        var generated = generatedSources.First();
        generated.HintName.Should().Be("LegacyCode_ValueObject.g.cs");
        var code = generated.SourceText.ToString();
        code.Should().Contain("sealed partial class LegacyCode");
    }

    [Fact]
    public void Generator_ShouldGenerateCode_ForTypeInGlobalNamespace()
    {
        var userSource = """

        [ValueObject]
        public readonly partial record struct GlobalVo
        {
            public static EricksonLopez.Result.Result<GlobalVo> Create(string value) =>
                EricksonLopez.Result.Result.Success(new GlobalVo());
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(1);
        var generated = generatedSources.First();
        generated.HintName.Should().Be("GlobalVo_ValueObject.g.cs");
        var code = generated.SourceText.ToString();
        code.Should().Contain("readonly partial record struct GlobalVo");
        code.Should().NotContain("namespace ");
    }

    [Fact]
    public void Generator_ShouldGenerateConversionOperators_WhenExplicitlyConfigured()
    {
        var userSource = """
        namespace ConversionDomain;


        [ValueObject(GenerateConversionOperators = true)]
        public readonly partial record struct Currency
        {
            public string Value { get; init; }
            public static EricksonLopez.Result.Result<Currency> Create(string value) =>
                EricksonLopez.Result.Result.Success(new Currency { Value = value });
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(1);
        var code = generatedSources.First().SourceText.ToString();
        code.Should().Contain("public static explicit operator string(Currency value) => value.Value;");
        code.Should().Contain("public static explicit operator Currency(string value) => Create(value).Value;");
    }

    [Fact]
    public void Generator_ShouldNotGenerateConversionOperators_WhenExplicitlySetToFalse()
    {
        var userSource = """
        namespace ConversionDomain;


        [ValueObject(GenerateConversionOperators = false)]
        public readonly partial record struct NoConvVo
        {
            public static EricksonLopez.Result.Result<NoConvVo> Create(string value) =>
                EricksonLopez.Result.Result.Success(new NoConvVo());
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(1);
        var code = generatedSources.First().SourceText.ToString();
        code.Should().NotContain("operator");
    }

    [Fact]
    public void Generator_ShouldIgnore_UnrecognizedNamedArgumentsOnAttribute()
    {
        var customAttrSource = """
        namespace EricksonLopez.ValueObjects;

        [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
        public sealed class ValueObjectAttribute : System.Attribute
        {
            public string? CustomNote { get; set; }
        }
        """;

        var userSource = """
        namespace ConversionDomain;


        [ValueObject(CustomNote = "SomeNote")]
        public readonly partial record struct OtherArgVo
        {
            public static EricksonLopez.Result.Result<OtherArgVo> Create(string value) =>
                EricksonLopez.Result.Result.Success(new OtherArgVo());
        }
        """;

        var syntaxTrees = new[]
        {
            CSharpSyntaxTree.ParseText(customAttrSource),
            CSharpSyntaxTree.ParseText(BaseInterfacesSource),
            CSharpSyntaxTree.ParseText(EnsureUsings(userSource))
        };

        var compilation = CSharpCompilation.Create(
            "OtherArgAssembly",
            syntaxTrees,
            CreateReferences(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new ValueObjectIncrementalGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        var runDriver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out var diagnostics);

        diagnostics.Should().BeEmpty();
        var runResult = runDriver.GetRunResult();
        runResult.GeneratedTrees.Should().HaveCount(1);
        var code = runResult.GeneratedTrees.First().ToString();
        code.Should().NotContain("operator");
    }

    [Fact]
    public void Generator_ShouldExtractValueType_FromSingleValueObjectBaseType_WithoutCreateMethod()
    {
        var userSource = """
        namespace ScalarDomain;


        [ValueObject(GenerateConversionOperators = true)]
        public sealed partial record class QuantityVo : SingleValueObject<QuantityVo, int>
        {
            private QuantityVo(int value) : base(value) {}
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(1);
        var code = generatedSources.First().SourceText.ToString();
        code.Should().Contain("public static explicit operator int(QuantityVo value) => value.Value;");
        code.Should().Contain("public static explicit operator QuantityVo(int value) => Create(value).Value;");
        code.Should().Contain("int? value = global::System.Text.Json.JsonSerializer.Deserialize<int>(ref reader, options);");
    }

    [Fact]
    public void Generator_ShouldExtractValueType_FromDeepInheritanceOfSingleValueObject_WithoutCreateMethod()
    {
        var userSource = """
        namespace DeepDomain;


        public abstract record IntermediateBase : SingleValueObject<IntermediateBase, long>
        {
            protected IntermediateBase(long value) : base(value) {}
        }

        [ValueObject(GenerateConversionOperators = true)]
        public sealed partial record class DeepLongVo : IntermediateBase
        {
            private DeepLongVo(long value) : base(value) {}
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(1);
        var code = generatedSources.First().SourceText.ToString();
        code.Should().Contain("public static explicit operator long(DeepLongVo value) => value.Value;");
        code.Should().Contain("public static explicit operator DeepLongVo(long value) => Create(value).Value;");
    }

    [Fact]
    public void Generator_ShouldExtractValueType_FromStringValueObjectBaseType_WithoutCreateMethod()
    {
        var userSource = """
        namespace StringDomain;


        [ValueObject(GenerateConversionOperators = true)]
        public sealed partial record class CustomerCode : StringValueObject<CustomerCode>
        {
            private CustomerCode(string value) : base(value) {}
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(1);
        var code = generatedSources.First().SourceText.ToString();
        code.Should().Contain("public static explicit operator string(CustomerCode value) => value.Value;");
        code.Should().Contain("public static explicit operator CustomerCode(string value) => Create(value).Value;");
        code.Should().Contain("string? value = global::System.Text.Json.JsonSerializer.Deserialize<string>(ref reader, options);");
    }

    [Fact]
    public void Generator_ShouldExtractValueType_FromCreateMethod_WhenNoBaseType()
    {
        var userSource = """
        namespace MethodDomain;


        [ValueObject(GenerateConversionOperators = true)]
        public readonly partial record struct Price
        {
            public decimal Value { get; init; }
            public static EricksonLopez.Result.Result<Price> Create(decimal value) =>
                EricksonLopez.Result.Result.Success(new Price { Value = value });
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(1);
        var code = generatedSources.First().SourceText.ToString();
        code.Should().Contain("public static explicit operator decimal(Price value) => value.Value;");
        code.Should().Contain("public static explicit operator Price(decimal value) => Create(value).Value;");
    }

    [Fact]
    public void Generator_ShouldDisambiguateCreateMethod_WhenMultipleOverloadsExist()
    {
        var userSource = """
        namespace OverloadDomain;


        [ValueObject(GenerateConversionOperators = true)]
        public readonly partial record struct OverloadedVo
        {
            public static EricksonLopez.Result.Result<OverloadedVo> Create(string a, string b) =>
                EricksonLopez.Result.Result.Success(new OverloadedVo());

            public EricksonLopez.Result.Result<OverloadedVo> Create(bool notStatic) =>
                EricksonLopez.Result.Result.Success(new OverloadedVo());

            public static EricksonLopez.Result.Result<OverloadedVo> Create(short singleParam) =>
                EricksonLopez.Result.Result.Success(new OverloadedVo());
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(1);
        var code = generatedSources.First().SourceText.ToString();
        code.Should().Contain("public static explicit operator short(OverloadedVo value) => value.Value;");
    }

    [Fact]
    public void Generator_ShouldExtractValueType_FromValueProperty_WhenNoCreateMethod()
    {
        var userSource = """
        namespace PropertyDomain;


        [ValueObject(GenerateConversionOperators = true)]
        public readonly partial record struct CustomDate
        {
            public DateTime Value { get; init; }
            public static CustomDate FromDate(DateTime value) => new() { Value = value };
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(1);
        var code = generatedSources.First().SourceText.ToString();
        code.Should().Contain("operator System.DateTime(CustomDate value) => value.Value;");
    }

    [Fact]
    public void Generator_ShouldFallbackToString_WhenNoCreateAndNoValueProp()
    {
        var userSource = """
        namespace FallbackDomain;


        [ValueObject(GenerateConversionOperators = true)]
        public readonly partial record struct FallbackVo
        {
            public int OtherProp { get; init; }
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(1);
        var code = generatedSources.First().SourceText.ToString();
        code.Should().Contain("public static explicit operator string(FallbackVo value) => value.Value;");
    }

    [Fact]
    public void Generator_ShouldHandle_MultipleTypesWithDistinctDeduplication()
    {
        var userSource = """
        namespace MultiDomain;


        [ValueObject]
        public readonly partial record struct FirstVo
        {
            public static EricksonLopez.Result.Result<FirstVo> Create(string v) => EricksonLopez.Result.Result.Success(new FirstVo());
        }

        [ValueObject]
        public readonly partial record struct SecondVo
        {
            public static EricksonLopez.Result.Result<SecondVo> Create(string v) => EricksonLopez.Result.Result.Success(new SecondVo());
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(2);
        generatedSources.Select(s => s.HintName).Should().Contain("FirstVo_ValueObject.g.cs");
        generatedSources.Select(s => s.HintName).Should().Contain("SecondVo_ValueObject.g.cs");
    }

    [Fact]
    public void Generator_ShouldGenerateCode_WhenAttributeIsNamed_ValueObjectAttribute_InGlobalNamespace()
    {
        var globalAttrSource = """
        [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct)]
        public sealed class ValueObjectAttribute : System.Attribute {}
        """;

        var userSource = """
        namespace CustomDomain;

        [ValueObjectAttribute]
        public readonly partial record struct GlobalAttrVo
        {
            public static EricksonLopez.Result.Result<GlobalAttrVo> Create(string value) =>
                EricksonLopez.Result.Result.Success(new GlobalAttrVo());
        }
        """;

        var syntaxTrees = new[]
        {
            CSharpSyntaxTree.ParseText(globalAttrSource),
            CSharpSyntaxTree.ParseText(BaseInterfacesSource),
            CSharpSyntaxTree.ParseText(userSource)
        };

        var references = CreateReferences();

        var compilation = CSharpCompilation.Create(
            "GlobalAttrAssembly",
            syntaxTrees,
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new ValueObjectIncrementalGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        var runDriver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out var diagnostics);

        diagnostics.Should().BeEmpty();
        var runResult = runDriver.GetRunResult();
        runResult.GeneratedTrees.Should().HaveCount(1);
        runResult.GeneratedTrees.First().ToString().Should().Contain("namespace CustomDomain");
        runResult.GeneratedTrees.First().ToString().Should().Contain("readonly partial record struct GlobalAttrVo");
    }

    [Fact]
    public void Generator_ShouldGenerateCode_WhenAttributeIsNamed_ValueObject_InGlobalNamespace()
    {
        var globalAttrSource = """
        [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct)]
        public sealed class ValueObject : System.Attribute {}
        """;

        var userSource = """
        namespace AnotherDomain;

        [ValueObject]
        public readonly partial record struct DirectValueObjectVo
        {
            public static EricksonLopez.Result.Result<DirectValueObjectVo> Create(string value) =>
                EricksonLopez.Result.Result.Success(new DirectValueObjectVo());
        }
        """;

        var syntaxTrees = new[]
        {
            CSharpSyntaxTree.ParseText(globalAttrSource),
            CSharpSyntaxTree.ParseText(BaseInterfacesSource),
            CSharpSyntaxTree.ParseText(userSource)
        };

        var references = CreateReferences();

        var compilation = CSharpCompilation.Create(
            "DirectValueObjectAssembly",
            syntaxTrees,
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new ValueObjectIncrementalGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        var runDriver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out var diagnostics);

        diagnostics.Should().BeEmpty();
        var runResult = runDriver.GetRunResult();
        runResult.GeneratedTrees.Should().HaveCount(1);
        runResult.GeneratedTrees.First().ToString().Should().Contain("namespace AnotherDomain");
        runResult.GeneratedTrees.First().ToString().Should().Contain("readonly partial record struct DirectValueObjectVo");
    }

    [Fact]
    public void Generator_ShouldIgnore_TypeWithAttributeInUnrelatedNamespace()
    {
        var otherNamespaceAttrSource = """
        namespace OtherUnrelatedNamespace
        {
            [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct)]
            public sealed class ValueObjectAttribute : System.Attribute {}
        }
        """;

        var userSource = """
        namespace MyDomain;

        [OtherUnrelatedNamespace.ValueObjectAttribute]
        public readonly partial record struct UnrelatedAttrVo
        {
            public static EricksonLopez.Result.Result<UnrelatedAttrVo> Create(string value) =>
                EricksonLopez.Result.Result.Success(new UnrelatedAttrVo());
        }
        """;

        var syntaxTrees = new[]
        {
            CSharpSyntaxTree.ParseText(otherNamespaceAttrSource),
            CSharpSyntaxTree.ParseText(BaseInterfacesSource),
            CSharpSyntaxTree.ParseText(userSource)
        };

        var compilation = CSharpCompilation.Create(
            "UnrelatedAttrAssembly",
            syntaxTrees,
            CreateReferences(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new ValueObjectIncrementalGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        var runDriver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out var diagnostics);

        diagnostics.Should().BeEmpty();
        var runResult = runDriver.GetRunResult();
        runResult.GeneratedTrees.Should().BeEmpty();
    }

    [Fact]
    public void Generator_ShouldIgnore_TypeWithoutValueObjectAttribute()
    {
        var userSource = """
        namespace MyDomain;

        public sealed class IgnoredEntity
        {
            public int Id { get; set; }
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().BeEmpty();
    }

    [Fact]
    public void Generator_ShouldIgnore_TypeWithDifferentAttribute()
    {
        var userSource = """
        namespace MyDomain;

        [System.Serializable]
        public sealed class SerializableEntity
        {
            public int Id { get; set; }
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().BeEmpty();
    }

    [Fact]
    public void Generator_WhenSourceHasNoCandidateTypes_ProducesNoSources()
    {
        var source = """
        namespace NonVoDomain;
        public class RegularClass { }
        public interface IRegularInterface { }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(source);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().BeEmpty();
    }

    [Fact]
    public void Generator_WhenSourceHasNonVoAttributes_ProducesNoSources()
    {
        var source = """
        namespace NonVoDomain;
        [System.Serializable]
        public class SerializableClass { }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(source);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().BeEmpty();
    }

    [Fact]
    public void IsCandidateType_WhenNodeHasNoAttributes_ReturnsFalse()
    {
        var syntaxTree = CSharpSyntaxTree.ParseText("public class NoAttributesClass {}");
        var classDeclaration = syntaxTree.GetRoot().DescendantNodes().OfType<TypeDeclarationSyntax>().Single();

        ValueObjectIncrementalGenerator.IsCandidateType(classDeclaration).Should().BeFalse();
    }

    [Fact]
    public void IsCandidateType_WhenNodeHasAttributes_ReturnsTrue()
    {
        var syntaxTree = CSharpSyntaxTree.ParseText("[Serializable] public class WithAttributesClass {}");
        var classDeclaration = syntaxTree.GetRoot().DescendantNodes().OfType<TypeDeclarationSyntax>().Single();

        ValueObjectIncrementalGenerator.IsCandidateType(classDeclaration).Should().BeTrue();
    }

    [Fact]
    public void FindValueObjectAttribute_WhenTypeHasNoValueObjectAttribute_ReturnsNull()
    {
        var syntaxTree = CSharpSyntaxTree.ParseText("[System.Serializable] public class PlainClass {}");
        var compilation = CSharpCompilation.Create("TestComp", [syntaxTree], CreateReferences());
        var model = compilation.GetSemanticModel(syntaxTree);
        var typeDecl = syntaxTree.GetRoot().DescendantNodes().OfType<TypeDeclarationSyntax>().Single();
        var typeSymbol = model.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol;

        var attr = ValueObjectIncrementalGenerator.FindValueObjectAttribute(typeSymbol!);
        attr.Should().BeNull();
    }

    [Fact]
    public void Generator_ShouldHandle_EmptyCompilation()
    {
        var compilation = CSharpCompilation.Create("EmptyTestAssembly");
        var generator = new ValueObjectIncrementalGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        var runDriver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out var diagnostics);

        diagnostics.Should().BeEmpty();
        var runResult = runDriver.GetRunResult();
        runResult.Results.SelectMany(r => r.GeneratedSources).Should().BeEmpty();
    }

    [Fact]
    [System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2075:DynamicallyAccessedMembers")]
    [System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2072:DynamicallyAccessedMembers")]
    public void GeneratedCode_ShouldCompile_AndExecuteAllGeneratedMethodsCorrectly()
    {
        var userSource = """
        namespace ExecutionDomain;


        [ValueObject(GenerateConversionOperators = true)]
        public readonly partial record struct ItemSku
        {
            public string Value { get; init; }

            public static EricksonLopez.Result.Result<ItemSku> Create(string value) =>
                !string.IsNullOrWhiteSpace(value) && value != "invalid"
                    ? EricksonLopez.Result.Result.Success(new ItemSku { Value = value })
                    : EricksonLopez.Result.Result.Failure<ItemSku>(EricksonLopez.Result.Error.Validation("InvalidSku", "SKU must not be empty or 'invalid'."));

            public static string TestSpanParse(string s) => Parse(System.MemoryExtensions.AsSpan(s), null).Value;
            public static bool TestSpanTryParse(string s, out ItemSku res) => TryParse(System.MemoryExtensions.AsSpan(s), null, out res);
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);
        diagnostics.Should().BeEmpty();

        using var ms = new MemoryStream();
        var emitResult = outputCompilation.Emit(ms);
        var errors = emitResult.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).Select(d => d.ToString()).ToList();
        emitResult.Success.Should().BeTrue(string.Join(Environment.NewLine, errors));

        var assembly = Assembly.Load(ms.ToArray());
        var skuType = assembly.GetType("ExecutionDomain.ItemSku")!;
        skuType.Should().NotBeNull();

        // 1. IParsable string Parse(string, IFormatProvider)
        var parseMethod = skuType.GetMethod("Parse", [typeof(string), typeof(IFormatProvider)]);
        parseMethod.Should().NotBeNull();

        var parsed = parseMethod!.Invoke(null, ["SKU-100", null]);
        parsed.Should().NotBeNull();
        skuType.GetProperty("Value")!.GetValue(parsed).Should().Be("SKU-100");

        // Parse null string throws ArgumentNullException
        var parseNull = () => parseMethod.Invoke(null, [null, null]);
        parseNull.Should().Throw<TargetInvocationException>().WithInnerException<ArgumentNullException>();

        // Parse invalid string throws FormatException
        var parseInvalid = () => parseMethod.Invoke(null, ["invalid", null]);
        parseInvalid.Should().Throw<TargetInvocationException>().WithInnerException<FormatException>()
            .WithMessage("Cannot parse 'invalid' as ItemSku: SKU must not be empty or 'invalid'.");

        // 2. IParsable TryParse(string, IFormatProvider, out T)
        var tryParseMethod = skuType.GetMethod("TryParse", [typeof(string), typeof(IFormatProvider), skuType.MakeByRefType()]);
        tryParseMethod.Should().NotBeNull();

        object?[] tryParseArgsSuccess = ["SKU-200", null, null];
        var successResult = (bool)tryParseMethod!.Invoke(null, tryParseArgsSuccess)!;
        successResult.Should().BeTrue();
        skuType.GetProperty("Value")!.GetValue(tryParseArgsSuccess[2]).Should().Be("SKU-200");

        object?[] tryParseArgsNull = [null, null, null];
        var nullResult = (bool)tryParseMethod.Invoke(null, tryParseArgsNull)!;
        nullResult.Should().BeFalse();

        object?[] tryParseArgsFail = ["invalid", null, null];
        var failResult = (bool)tryParseMethod.Invoke(null, tryParseArgsFail)!;
        failResult.Should().BeFalse();

        // 3. ISpanParsable ReadOnlySpan<char> Parse(ReadOnlySpan<char>, IFormatProvider)
        var testSpanParse = skuType.GetMethod("TestSpanParse", [typeof(string)]);
        testSpanParse.Should().NotBeNull();

        var spanParsed = testSpanParse!.Invoke(null, ["SKU-300"]);
        spanParsed.Should().Be("SKU-300");

        var parseSpanInvalid = () => testSpanParse.Invoke(null, ["invalid"]);
        parseSpanInvalid.Should().Throw<TargetInvocationException>().WithInnerException<FormatException>()
            .WithMessage("Cannot parse 'invalid' as ItemSku: SKU must not be empty or 'invalid'.");

        // 4. ISpanParsable TryParse(ReadOnlySpan<char>, IFormatProvider, out T)
        var testSpanTryParse = skuType.GetMethod("TestSpanTryParse", [typeof(string), skuType.MakeByRefType()]);
        testSpanTryParse.Should().NotBeNull();

        object?[] spanArgsSuccess = ["SKU-400", null];
        var spanSuccessResult = (bool)testSpanTryParse!.Invoke(null, spanArgsSuccess)!;
        spanSuccessResult.Should().BeTrue();
        skuType.GetProperty("Value")!.GetValue(spanArgsSuccess[1]).Should().Be("SKU-400");

        object?[] spanArgsFail = ["invalid", null];
        var spanFailResult = (bool)testSpanTryParse.Invoke(null, spanArgsFail)!;
        spanFailResult.Should().BeFalse();

        // 5. Explicit Operators
        var opExplicitToString = skuType.GetMethods(BindingFlags.Public | BindingFlags.Static)
            .FirstOrDefault(m => m.Name == "op_Explicit" && m.ReturnType == typeof(string));
        opExplicitToString.Should().NotBeNull();
        var strVal = opExplicitToString!.Invoke(null, [parsed]);
        strVal.Should().Be("SKU-100");

        var opExplicitToVo = skuType.GetMethods(BindingFlags.Public | BindingFlags.Static)
            .FirstOrDefault(m => m.Name == "op_Explicit" && m.ReturnType == skuType);
        opExplicitToVo.Should().NotBeNull();
        var voVal = opExplicitToVo!.Invoke(null, ["SKU-500"]);
        skuType.GetProperty("Value")!.GetValue(voVal).Should().Be("SKU-500");

        // 6. System.Text.Json Serialization & Deserialization
        var jsonConverterType = assembly.GetType("ExecutionDomain.ItemSku+ItemSkuJsonConverter")
            ?? assembly.GetType("ExecutionDomain.ItemSkuJsonConverter");
        jsonConverterType.Should().NotBeNull();

        var jsonOptions = new JsonSerializerOptions();
        var converterInstance = (JsonConverter)Activator.CreateInstance(jsonConverterType!)!;
        jsonOptions.Converters.Add(converterInstance);

        var json = JsonSerializer.Serialize(parsed, jsonOptions);
        json.Should().Be("\"SKU-100\"");

        var deserialized = JsonSerializer.Deserialize(json, skuType, jsonOptions);
        skuType.GetProperty("Value")!.GetValue(deserialized).Should().Be("SKU-100");

        var actNullJson = () => JsonSerializer.Deserialize("null", skuType, jsonOptions);
        actNullJson.Should().Throw<JsonException>();

        var actInvalidJson = () => JsonSerializer.Deserialize("\"invalid\"", skuType, jsonOptions);
        actInvalidJson.Should().Throw<JsonException>();
    }

    [Fact]
    public void Generator_ShouldGenerateCode_ForFileScopedRecordStruct()
    {
        var userSource = """
        namespace MyDomain;

        using EricksonLopez.ValueObjects;

        [ValueObject]
        file readonly partial record struct LocalSecretCode
        {
            public static EricksonLopez.Result.Result<LocalSecretCode> Create(string value) =>
                EricksonLopez.Result.Result.Success(new LocalSecretCode());
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(1);
        var generated = generatedSources.First();
        generated.HintName.Should().Be("LocalSecretCode_ValueObject.g.cs");
        var code = generated.SourceText.ToString();
        code.Should().Contain("file readonly partial record struct LocalSecretCode");
        code.Should().Contain("file sealed class LocalSecretCodeJsonConverter");
    }

    [Fact]
    public void Generator_ShouldGenerateCode_ForInternalRecordClass()
    {
        var userSource = """
        namespace MyDomain;

        using EricksonLopez.ValueObjects;

        [ValueObject]
        internal sealed partial record class InternalTenantKey
        {
            public static EricksonLopez.Result.Result<InternalTenantKey> Create(string value) =>
                EricksonLopez.Result.Result.Success(new InternalTenantKey());
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);

        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(1);
        var generated = generatedSources.First();
        generated.HintName.Should().Be("InternalTenantKey_ValueObject.g.cs");
        var code = generated.SourceText.ToString();
        code.Should().Contain("sealed partial record class InternalTenantKey");
        code.Should().Contain("public sealed class InternalTenantKeyJsonConverter");
    }

    [Fact]
    public void Generator_WhenCompiled_EmitsExecutableAssemblyWithWorkingParsableMethods()
    {
        var userSource = """
        namespace MyDomain;

        using EricksonLopez.ValueObjects;
        using EricksonLopez.Result;

        [ValueObject]
        public readonly partial record struct ProductSku
        {
            public string Code { get; }
            private ProductSku(string code) => Code = code;

            public static Result<ProductSku> Create(string? value)
            {
                if (string.IsNullOrWhiteSpace(value))
                    return Result<ProductSku>.Failure(Error.Validation("ProductSku.Required", "SKU cannot be empty."));

                return Result<ProductSku>.Success(new ProductSku(value.Trim().ToUpperInvariant()));
            }

            public static Result<ProductSku> Create(System.ReadOnlySpan<char> value) =>
                Create(value.ToString());
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);
        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(1);

        var assembly = CompileAndEmitAssembly(outputCompilation);
        var skuType = assembly.GetType("MyDomain.ProductSku");
        skuType.Should().NotBeNull();

        // 1. Validate Parse(string)
        var parseMethod = skuType!.GetMethod("Parse", [typeof(string), typeof(IFormatProvider)]);
        parseMethod.Should().NotBeNull();
        var parsedInstance = parseMethod!.Invoke(null, ["sku-123-abc", null]);
        parsedInstance.Should().NotBeNull();

        var codeProp = skuType.GetProperty("Code");
        codeProp!.GetValue(parsedInstance).Should().Be("SKU-123-ABC");

        // 2. Validate TryParse(string, out result)
        var tryParseMethod = skuType.GetMethod("TryParse", [typeof(string), typeof(IFormatProvider), skuType.MakeByRefType()]);
        tryParseMethod.Should().NotBeNull();

        object?[] tryParseSuccessArgs = ["sku-456", null, null];
        var successResult = (bool)tryParseMethod!.Invoke(null, tryParseSuccessArgs)!;
        successResult.Should().BeTrue();
        codeProp.GetValue(tryParseSuccessArgs[2]).Should().Be("SKU-456");

        object?[] tryParseFailArgs = ["", null, null];
        var failResult = (bool)tryParseMethod.Invoke(null, tryParseFailArgs)!;
        failResult.Should().BeFalse();
    }

    [Fact]
    public void Generator_WhenCompiled_EmitsExecutableJsonConverterForRecordClass()
    {
        var userSource = """
        namespace MyDomain;

        using EricksonLopez.ValueObjects;
        using EricksonLopez.Result;

        [ValueObject]
        public sealed partial record class AccountCode
        {
            public string Value { get; }
            private AccountCode(string value) => Value = value;

            public static Result<AccountCode> Create(string? value)
            {
                if (string.IsNullOrWhiteSpace(value))
                    return Result<AccountCode>.Failure(Error.Validation("AccountCode.Required", "Code is required."));

                return Result<AccountCode>.Success(new AccountCode(value.Trim()));
            }

            public static Result<AccountCode> Create(System.ReadOnlySpan<char> value) =>
                Create(value.ToString());

            public override string ToString() => Value;
        }
        """;

        var (outputCompilation, generatedSources, diagnostics) = RunGenerator(userSource);
        diagnostics.Should().BeEmpty();
        generatedSources.Should().HaveCount(1);

        var assembly = CompileAndEmitAssembly(outputCompilation);
        var accountType = assembly.GetType("MyDomain.AccountCode");
        accountType.Should().NotBeNull();

        var createMethod = accountType!.GetMethod("Create", [typeof(string)]);
        var createResult = createMethod!.Invoke(null, ["ACC-998877"]);
        var valueProp = createResult!.GetType().GetProperty("Value");
        var accountInstance = valueProp!.GetValue(createResult);

        // Serialize to JSON
        string json = JsonSerializer.Serialize(accountInstance, accountType);
        json.Should().Be("\"ACC-998877\"");

        // Deserialize from JSON
        var deserialized = JsonSerializer.Deserialize(json, accountType);
        deserialized.Should().NotBeNull();
        deserialized.Should().Be(accountInstance);
    }

    private static Assembly CompileAndEmitAssembly(Compilation compilation)
    {
        using var ms = new MemoryStream();
        var emitResult = compilation.Emit(ms);
        if (!emitResult.Success)
        {
            var errors = string.Join("\n", emitResult.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).Select(d => d.ToString()));
            throw new InvalidOperationException($"Compilation failed with errors:\n{errors}");
        }

        ms.Seek(0, SeekOrigin.Begin);
        return Assembly.Load(ms.ToArray());
    }

    private static MetadataReference[] CreateReferences() =>
    [
        MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
        MetadataReference.CreateFromFile(typeof(Attribute).Assembly.Location),
        MetadataReference.CreateFromFile(typeof(IParsable<>).Assembly.Location),
        MetadataReference.CreateFromFile(typeof(ISpanParsable<>).Assembly.Location),
        MetadataReference.CreateFromFile(typeof(EricksonLopez.Result.Result).Assembly.Location),
        MetadataReference.CreateFromFile(typeof(JsonSerializer).Assembly.Location),
        MetadataReference.CreateFromFile(typeof(JsonConverter).Assembly.Location),
        MetadataReference.CreateFromFile(Path.Combine(Path.GetDirectoryName(typeof(object).Assembly.Location)!, "System.Runtime.dll"))
    ];

    private static string EnsureUsings(string source)
    {
        var usings = "";
        if (!source.Contains("using System;")) usings += "using System;\n";
        if (!source.Contains("using EricksonLopez.ValueObjects;")) usings += "using EricksonLopez.ValueObjects;\n";
        return usings.Length > 0 ? usings + source : source;
    }

    private static (Compilation OutputCompilation, IReadOnlyList<GeneratedSourceResult> GeneratedSources, ImmutableArray<Diagnostic> Diagnostics) RunGenerator(string userSource)
    {
        var syntaxTrees = new[]
        {
            CSharpSyntaxTree.ParseText(ValueObjectAttributeSource),
            CSharpSyntaxTree.ParseText(BaseInterfacesSource),
            CSharpSyntaxTree.ParseText(EnsureUsings(userSource))
        };

        var compilation = CSharpCompilation.Create(
            "GeneratorTestAssembly",
            syntaxTrees,
            CreateReferences(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new ValueObjectIncrementalGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        var runDriver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out var diagnostics);

        var runResult = runDriver.GetRunResult();
        var generatedSources = runResult.Results.SelectMany(r => r.GeneratedSources).ToList();

        return (outputCompilation, generatedSources, diagnostics);
    }
}






